create table "opa_properties" (
  "parcel" integer,
  "loc" varchar(32),
  "owner1" varchar(32) null,
  "owner2" varchar(32) null,
  "census" varchar(8),
  "zip" varchar(16) null,
  "wd_geo" integer null,
  "st_cd" integer,
  "house_no" integer,
  "suff" varchar(4) null,
  "unit" varchar(16) null,
  "ext" integer,
  "rcd_dt" integer,
  "sale_date" integer,
  "sale_pr" integer,
  "sale_ty" varchar(4) null,
  "unf" varchar(4) null,
  "assmt_dt" integer,
  "mv_dt" integer,
  "mv" integer,
  "tx_lnd" integer,
  "tx_bldg" integer,
  "xmpt_lnd" integer,
  "xmpt_bldg" integer,
  "cat_cd" integer,
  "xmpt_cd" varchar(8) null,
  "xmpt_dt" integer,
  "bldg_cd" varchar(8),
  "zone" varchar(8) null,
  "lnd_use" integer null,
  "des_area" varchar(8) null,
  "area_use" varchar(4) null,
  "site_typ" varchar(4) null,
  "frt" real,
  "dpt" real,
  "shp" varchar(4) null,
  "tot_area" real,
  "top" varchar(4) null,
  "grg_typ" varchar(4) null,
  "grg_sp" integer,
  "off_st" integer,
  "view" varchar(4) null,
  "otr_bldg" varchar(4) null,
  "stories" real,
  "gen_const" varchar(4) null,
  "typ_dwell" varchar(4) null,
  "dt_ext_cond" integer,
  "ext_cond" integer null,
  "qlt_grd" integer null,
  "yr_built" varchar(4) null,
  "est_yr_blt" varchar(4) null,
  "flr_plan" varchar(4) null,
  "no_rm" real,
  "no_bd" real,
  "no_bath" real,
  "basmt" varchar(4) null,
  "basmt_sqft" integer,
  "fire" integer,
  "typ_heat" varchar(4) null,
  "fuel" varchar(4) null,
  "cnt_air" varchar(4) null,
  "int_cond" integer null,
  "amty" varchar(8) null,
  "typ_imp" varchar(4) null,
  "utly" varchar(4) null,
  "sew" varchar(4) null,
  "sep_uts" varchar(4) null,
  "tot_liv_area" integer,
  "off_prop" varchar(4) null,
  "bk_pg" varchar(16) null,
  "reg_no" varchar(32) null,
  "cross_ref" varchar(16) null,
  "end" varchar(4),
  "category_code_description" varchar(4) null
)
